export { useGarage, getActiveBikeIdSnapshot, getBikeSnapshot } from './hooks/useGarage';
export { useBikeStats } from './hooks/useBikeStats';
export { GarageDiorama } from './components/GarageDiorama';
export { MechaNick } from './components/MechaNick';
export { BikePhotoCapture } from './components/BikePhotoCapture';
export { StatsPanel } from './components/StatsPanel';
export { MaintenanceList } from './components/MaintenanceList';
export type { Bike, BikePhotos, MaintItem, GarageState } from './types';
export { serviceStatus, dueItems } from './lib/serviceReminders';
export type { ServiceStatus } from './lib/serviceReminders';
